# Generated by Django 5.2.2 on 2026-04-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_auto_20201103_1024"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="business",
            field=models.TextField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="cons",
            field=models.TextField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="pros",
            field=models.TextField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="post",
            name="rationale",
            field=models.TextField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="vote",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
